version: "3.1"

services:
  api:
    image: chaikinnpong/trial:csilms-sprboot
    ports:
      - "80:80"
    network_mode: 'host'

  frontend:
    image: chaikinnpong/trial:csilms-ngix
    ports:
      - "3000:3000"
    depends_on:
      - api
